baseURL = "https://cho260526.github.io/"
languageCode = "ko-kr"
title = "My Portfolio"
theme = "PaperMod"

[services.googleAnalytics]
   id = "G-VWZYV3BDN4"

[params]
 googleSiteVerify = "2oCrZINCh-1uj2XEG7cz545wG-D61APt89uo2cwZSCU"
  author = "cho260526"
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
